### DSC 540 - Data Preparation
### Week 7 & 8 Exercises

The four chapters you read these two weeks focus extensively on cleaning and transforming data.

You can choose from either of these two datasets:

So Much Candy Data, Seriously. (Ng, 2017)
- The Metropolitan Museum of Art Open Access CSV.  (Github, 2019 (this data set has multiple years’ worth of data – you can use these files for merging/joining)
- You can also download all of the above data from both sites directly from this link: Weeks 7 & 8 Datasets

For this assignment you need to complete 8 of the following exercises against this data.

Note: You must select at least two methods from each chapter to perform on one of the datasets. You are welcome to do more methods and you do not have to use the same dataset for all 8 methods.

Chapter 7
- Filter out missing data
- Fill in missing data
- Remove duplicates
- Transform data using either mapping or a function
- Replace values
- Discretization and Binning
- Manipulate Strings

Chapter 8
- Create hierarchical index
- Combine and Merge Datasets (you will have to either create a new dataset from your existing data or create a relationship between the data I have provided)
- Reshape
- Pivot the data

Chapter 10
- Grouping with Dicts/Series
- Grouping with Functions
- Grouping with Index Levels
- Split/Apply/Combine
- Cross Tabs

Chapter 11
- Convert between string and date time
- Generate date range
- Frequencies and date offsets
- Convert timestamps to periods and back
- Period Frequency conversions

In [1]:
# Import Libraries
import pandas as pd
import numpy as np

# Read in file
metobj_df = pd.read_csv("C:/Users/Ashem/OneDrive/Desktop/Masters Program - DSC/DSC 540 - Data Preparation/Week 7&8 Data/MetObjects.csv")

# Preview file
metobj_df.head()

C:\Users\Ashem\AppData\Local\Temp\ipykernel_36936\3196131170.py:6: DtypeWarning: Columns (5,7,10,11,12,13,14,34,35,36,37,38,39,40,41,42,43,44,45,46) have mixed types. Specify dtype option on import or set low_memory=False.
  metobj_df = pd.read_csv("C:/Users/Ashem/OneDrive/Desktop/Masters Program - DSC/DSC 540 - Data Preparation/Week 7&8 Data/MetObjects.csv")

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

Ch 7 transformations

- Filter out missing data
- bin by Accession Year (not actually, went with manipulating the strings instead for reasons later explained)

In [2]:
# Check out the data
metobj_df.info

<bound method DataFrame.info of        Object Number  Is Highlight  Is Timeline Work  Is Public Domain  \
0         1979.486.1         False             False             False
1         1980.264.5         False             False             False
2           67.265.9         False             False             False
3          67.265.10         False             False             False
4          67.265.11         False             False             False
...              ...           ...               ...               ...
484951    55.621.134         False             False             False
484952      1977.646         False             False             False
484953       33.40.1         False             False             False
484954     170.1 C42          True             False             False
484955     17.3.3457         False             False             False

        Object ID Gallery Number           Department AccessionYear  \
0               1            NaN    The American Wing        1979.0
1               2            NaN    The American Wing        1980.0
2               3            NaN    The American Wing        1967.0
3               4            NaN    The American Wing        1967.0
4               5            NaN    The American Wing        1967.0
...           ...            ...                  ...           ...
484951     900605            NaN  Drawings and Prints          1955
484952     900606            NaN  Drawings and Prints          1977
484953     900633            NaN  Drawings and Prints          1933
484954     900717            NaN        The Libraries           NaN
484955     900748            NaN  Drawings and Prints          1917

       Object Name                                              Title  ...  \
0             Coin                       One-dollar Liberty Head Coin  ...
1             Coin                       Ten-dollar Liberty Head Coin  ...
2             Coin                         Two-and-a-Half Dollar Coin  ...
3             Coin                         Two-and-a-Half Dollar Coin  ...
4             Coin                         Two-and-a-Half Dollar Coin  ...
...            ...                                                ...  ...
484951       Print                                       Holiday Card  ...
484952       Print                                     Brooklyn Local  ...
484953       Print                                Yesterday and Today  ...
484954         NaN  De la loi du contraste simultané des couleurs,...  ...
484955       Print  Madison Square - Fifth Avenue and Broadway at ...  ...

       River Classification Rights and Reproduction  \
0        NaN            NaN                     NaN
1        NaN            NaN                     NaN
2        NaN            NaN                     NaN
3        NaN            NaN                     NaN
4        NaN            NaN                     NaN
...      ...            ...                     ...
484951   NaN         Prints                     NaN
484952   NaN         Prints                     NaN
484953   NaN         Prints                     NaN
484954   NaN            NaN                     NaN
484955   NaN         Prints                     NaN

                                            Link Resource Object Wikidata URL  \
0        http://www.metmuseum.org/art/collection/search/1                 NaN
1        http://www.metmuseum.org/art/collection/search/2                 NaN
2        http://www.metmuseum.org/art/collection/search/3                 NaN
3        http://www.metmuseum.org/art/collection/search/4                 NaN
4        http://www.metmuseum.org/art/collection/search/5                 NaN
...                                                   ...                 ...
484951  http://www.metmuseum.org/art/collection/search...                 NaN
484952  http://www.metmuseum.org/art/collection/search...                 NaN
484953  http://www.metmuseum.org/art/collection/search...                 NaN
484954  http://www.metmuseum.org/art/collection/search...                 NaN
484955  http://www.metmuseum.org/art/collection/search...                 NaN

       Metadata Date                                Repository Tags  \
0                NaN  Metropolitan Museum of Art, New York, NY  NaN
1                NaN  Metropolitan Museum of Art, New York, NY  NaN
2                NaN  Metropolitan Museum of Art, New York, NY  NaN
3                NaN  Metropolitan Museum of Art, New York, NY  NaN
4                NaN  Metropolitan Museum of Art, New York, NY  NaN
...              ...                                       ...  ...
484951           NaN  Metropolitan Museum of Art, New York, NY  NaN
484952           NaN  Metropolitan Museum of Art, New York, NY  NaN
484953           NaN  Metropolitan Museum of Art, New York, NY  NaN
484954           NaN  Metropolitan Museum of Art, New York, NY  NaN
484955           NaN  Metropolitan Museum of Art, New York, NY  NaN

       Tags AAT URL Tags Wikidata URL
0               NaN               NaN
1               NaN               NaN
2               NaN               NaN
3               NaN               NaN
4               NaN               NaN
...             ...               ...
484951          NaN               NaN
484952          NaN               NaN
484953          NaN               NaN
484954          NaN               NaN
484955          NaN               NaN

[484956 rows x 54 columns]>

In [3]:
# Determine how many na values exist
metobj_df.isna().sum()

Object Number                   0
Is Highlight                    0
Is Timeline Work                0
Is Public Domain                0
Object ID                       0
Gallery Number             435415
Department                      0
AccessionYear                3862
Object Name                  2266
Title                       28803
Culture                    276766
Period                     393813
Dynasty                    461755
Reign                      473720
Portfolio                  458442
Constituent ID             202443
Artist Role                202443
Artist Prefix              202443
Artist Display Name        202443
Artist Display Bio         204533
Artist Suffix              202491
Artist Alpha Sort          202443
Artist Nationality         202443
Artist Begin Date          202443
Artist End Date            202443
Artist Gender              378474
Artist ULAN URL            257515
Artist Wikidata URL        260754
Object Date                 13431
Object Begin Date               0
Object End Date                 0
Medium                       7215
Dimensions                  75058
Credit Line                   651
Geography Type             424997
City                       452202
State                      482335
County                     476397
Country                    408949
Region                     453456
Subregion                  462813
Locale                     469217
Locus                      477438
Excavation                 468385
River                      482864
Classification              78717
Rights and Reproduction    460427
Link Resource                   0
Object Wikidata URL        415802
Metadata Date              484956
Repository                      0
Tags                       292501
Tags AAT URL               292501
Tags Wikidata URL          292501
dtype: int64

In [4]:
# drop the na values
metobj_df.dropna()

Empty DataFrame
Columns: [Object Number, Is Highlight, Is Timeline Work, Is Public Domain, Object ID, Gallery Number, Department, AccessionYear, Object Name, Title, Culture, Period, Dynasty, Reign, Portfolio, Constituent ID, Artist Role, Artist Prefix, Artist Display Name, Artist Display Bio, Artist Suffix, Artist Alpha Sort, Artist Nationality, Artist Begin Date, Artist End Date, Artist Gender, Artist ULAN URL, Artist Wikidata URL, Object Date, Object Begin Date, Object End Date, Medium, Dimensions, Credit Line, Geography Type, City, State, County, Country, Region, Subregion, Locale, Locus, Excavation, River, Classification, Rights and Reproduction, Link Resource, Object Wikidata URL, Metadata Date, Repository, Tags, Tags AAT URL, Tags Wikidata URL]
Index: []

[0 rows x 54 columns]

In [5]:
# determine if we can bin by Accession Year
metobj_df["AccessionYear"].unique()

array([1979.0, 1980.0, 1967.0, 1916.0, 1909.0, 1964.0, 1970.0, 1904.0,
       1976.0, 1938.0, 1918.0, 1946.0, 1960.0, 1910.0, 1922.0, 1923.0,
       1930.0, 1934.0, 1936.0, 1937.0, 1939.0, 1941.0, 1947.0, 1948.0,
       1949.0, 1971.0, 1984.0, 1989.0, 1985.0, 1952.0, 1968.0, 1919.0,
       nan, 1978.0, 1972.0, 1924.0, 1983.0, 1950.0, 1925.0, 1926.0,
       1931.0, 1932.0, 1951.0, 1953.0, 2006.0, 1969.0, 1975.0, 1981.0,
       1986.0, 1959.0, 1944.0, 1982.0, 1945.0, 1888.0, 1911.0, 1957.0,
       1943.0, 1935.0, 1917.0, 1973.0, 1940.0, 1913.0, 1962.0, 1914.0,
       1966.0, 1954.0, 1920.0, 1933.0, 2014.0, 1928.0, 1901.0, 1958.0,
       1965.0, 1883.0, 1902.0, 1987.0, 1974.0, 1977.0, 1915.0, 1942.0,
       1912.0, 1927.0, 1896.0, 1892.0, 1877.0, 1906.0, 1955.0, 1961.0,
       1994.0, 1907.0, 1929.0, 2018.0, 1921.0, 1908.0, 1963.0, 2010.0,
       2000.0, 1988.0, 2021.0, 1956.0, 2012.0, 2013.0, 2002.0, 1999.0,
       1894.0, 1897.0, 1993.0, 1893.0, 1992.0, 1996.0, 1898.0, 1899.0,
       1991.0, 2020.0, 1880.0, 1890.0, 1876.0, 1886.0, 1895.0, 1997.0,
       2019.0, 1990.0, 2022.0, 1891.0, 1881.0, 1903.0, 1900.0, 1905.0,
       1995.0, 1887.0, 2011.0, 1874.0, 1885.0, 1873.0, 1884.0, 1882.0,
       1875.0, 1872.0, 2001.0, 1889.0, 2008.0, 2007.0, 2015.0, 1998.0,
       2003.0, 2005.0, 2016.0, 2004.0, 2017.0, 2009.0, 1879.0, 1870.0,
       '1933', '1935', '1936', '1937', '1938', '1939', '1940', '1941',
       '1942', '1943', '1944', '1945', '1946', '1947', '1948', '1949',
       '1950', '1951', '1952', '1953', '1954', '1955', '1956', '1957',
       '1958', '1959', '1960', '1961', '1962', '1963', '1964', '1965',
       '1966', '1967', '1968', '1969', '1883', '1997', '1996', '1981',
       '1978', '1980', '1985', '1983', '1979', '1991', '1993', '1990',
       '1994', '2014', '2020', '2015', '2021', '2018', '2019', '2017',
       '2022', '1995', '2000', '1984', '1998', '1918', '1972', '1999',
       '1975', '1989', '1987', '1973', '1974', '1982', '2001', '2003',
       '2010', '2013', '2002', '1992', '1976', '2004', '2005', '1970',
       '1977', '2005-02-15', '2006', '2011', '2007', '2008', '2009',
       1878.0, 1871.0, '1920', '1921', '1922', '1923', '1924', '1925',
       '1926', '1927', '1928', '1929', '1930', '1931', '1932', '1934',
       '2016', '1986', '1988', '2012', '1971', '1909', '1889', '1906',
       '1894', '1907', '1908', '1910', '1911', '1912', '1915', '1913',
       '1914', '2022-05-20', '1916', '1917', '1919', '1904', '1898',
       '1905', '1899', '1874', '1890', '1886', '1901', '1902', '1903',
       '1896', '1900', 2023.0, '2023', '1891', '1893', '2022-02-09',
       '1953-05-28', '1956-08-24', '1885', '1978-12-12', '1977-08-08',
       '1980-06-18', '1978-03-07', '1963-06-17', '1959-10-16',
       '1960-11-15', '1960-06-25', '1961-01-10', '1968-12-12',
       '1966-04-29', '1967-08-12', '1967-12-04', '1969-07-10',
       '1969-07-17', '1970-09-08', '1950-07-21', '1953-01-19',
       '1955-05-24', '1962-10-15', '1959-12-28'], dtype=object)

In [6]:
# Values aren't clean so we have to manipulate the string to clean them
# strip whitespace
metobj_df.columns = metobj_df.columns.str.strip()

In [7]:
# Convert to string
col = metobj_df["AccessionYear"].astype(str).str.strip()

# extract the year from each value
years = col.str.extract(r"(\d{4})")[0]

# ensure the years are numeric
metobj_df["AccessionYear_clean"] = pd.to_numeric(years, errors="coerce")

# injection due to noticing a stray "." after my values & it bugged me
metobj_df["AccessionYear_clean"] = (
    metobj_df["AccessionYear_clean"].astype("Int64")
)

# no need to bin if I did the manipulate strings part of Ch7

In [8]:
# relook at Accession Year
metobj_df["AccessionYear_clean"].unique()

<IntegerArray>
[1979, 1980, 1967, 1916, 1909, 1964, 1970, 1904, 1976, 1938,
 ...
 2005, 2016, 2004, 2017, 2009, 1879, 1870, 1878, 1871, 2023]
Length: 155, dtype: Int64

Ch 10 transformations

- Grouping with Dicts/Series
- Cross Tab

In [9]:
# Determine departments
metobj_df["Department"].unique()

array(['The American Wing', 'European Sculpture and Decorative Arts',
       'Modern and Contemporary Art', 'Arms and Armor', 'Medieval Art',
       'Asian Art', 'Islamic Art', 'Costume Institute',
       'Arts of Africa, Oceania, and the Americas', 'Drawings and Prints',
       'Greek and Roman Art', 'Photographs', 'Ancient Near Eastern Art',
       'Egyptian Art', 'European Paintings', 'Robert Lehman Collection',
       'The Cloisters', 'Musical Instruments', 'The Libraries'],
      dtype=object)

In [10]:
# Create the groups
Dept_Groups = {
    "The American Wing": "Western Art",
    "European Sculpture and Decorative Arts": "Western Art",
    "European Paintings": "Western Art",
    "Greek and Roman Art": "Ancient Western",
    "Ancient Near Eastern Art": "Ancient",
    "Egyptian Art": "Ancient",
    "Medieval Art": "Historical",
    "Arms and Armor": "Historical",
    "Asian Art": "Non-Western",
    "Islamic Art": "Non-Western",
    "Arts of Africa, Oceania, and the Americas": "Non-Western",
    "Modern and Contemporary Art": "Modern",
    "Drawings and Prints": "Works on Paper",
    "Photographs": "Works on Paper",
    "Costume Institute": "Special Collections",
    "Musical Instruments": "Special Collections",
    "The Libraries": "Special Collections",
    "Robert Lehman Collection": "Special Collections",
    "The Cloisters": "Historical"
}

In [11]:
# apply the grouping
metobj_df["Dept_Group"] = metobj_df["Department"].map(Dept_Groups)

In [12]:
# create a cross tab
metobj_df["Dept_Group"].value_counts()

Dept_Group
Works on Paper         210089
Non-Western             64940
Western Art             64209
Special Collections     39999
Ancient                 34192
Ancient Western         33726
Historical              23105
Modern                  14696
Name: count, dtype: int64

In [13]:
# preview
metobj_df.head()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL,AccessionYear_clean,Dept_Group
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979.0,Coin,One-dollar Liberty Head Coin,...,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1979,Western Art
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980.0,Coin,Ten-dollar Liberty Head Coin,...,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1980,Western Art
2,67.265.9,False,False,False,3,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1967,Western Art
3,67.265.10,False,False,False,4,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1967,Western Art
4,67.265.11,False,False,False,5,NaN,The American Wing,1967.0,Coin,Two-and-a-Half Dollar Coin,...,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN,1967,Western Art

You may be wondering why chapter 10's transformations & cleanings are before chapter 8; it's because I went through and did ones I had recently performed, and then went back and did other actions. However, a little fun fact I forgot about, when you restart your kernel and then rerun the blocks in order, an index creation will 100% cause an error when you try to group on that column later. So I rearranged them. In hindsight, I could have duplicated the column and grouped it off of that one, though. I'll have to keep that in mind for the future.

Ch 8 transformations

- Create Hierarchical Index
- Pivot the Data

In [14]:
# Set the index
metobj_df = metobj_df.set_index(["Department", "Object Number"])

In [15]:
# Pivot the data
pivot = metobj_df.reset_index().pivot_table(
    index="Department",
    values="Object Number",
    aggfunc="count"
)

In [16]:
# preview
metobj_df.head()

                                 Is Highlight  Is Timeline Work  \
Department        Object Number
The American Wing 1979.486.1            False             False
                  1980.264.5            False             False
                  67.265.9              False             False
                  67.265.10             False             False
                  67.265.11             False             False

                                 Is Public Domain  Object ID Gallery Number  \
Department        Object Number
The American Wing 1979.486.1                False          1            NaN
                  1980.264.5                False          2            NaN
                  67.265.9                  False          3            NaN
                  67.265.10                 False          4            NaN
                  67.265.11                 False          5            NaN

                                AccessionYear Object Name  \
Department        Object Number
The American Wing 1979.486.1           1979.0        Coin
                  1980.264.5           1980.0        Coin
                  67.265.9             1967.0        Coin
                  67.265.10            1967.0        Coin
                  67.265.11            1967.0        Coin

                                                        Title Culture Period  \
Department        Object Number
The American Wing 1979.486.1     One-dollar Liberty Head Coin     NaN    NaN
                  1980.264.5     Ten-dollar Liberty Head Coin     NaN    NaN
                  67.265.9         Two-and-a-Half Dollar Coin     NaN    NaN
                  67.265.10        Two-and-a-Half Dollar Coin     NaN    NaN
                  67.265.11        Two-and-a-Half Dollar Coin     NaN    NaN

                                 ... Rights and Reproduction  \
Department        Object Number  ...
The American Wing 1979.486.1     ...                     NaN
                  1980.264.5     ...                     NaN
                  67.265.9       ...                     NaN
                  67.265.10      ...                     NaN
                  67.265.11      ...                     NaN

                                                                    Link Resource  \
Department        Object Number
The American Wing 1979.486.1     http://www.metmuseum.org/art/collection/search/1
                  1980.264.5     http://www.metmuseum.org/art/collection/search/2
                  67.265.9       http://www.metmuseum.org/art/collection/search/3
                  67.265.10      http://www.metmuseum.org/art/collection/search/4
                  67.265.11      http://www.metmuseum.org/art/collection/search/5

                                Object Wikidata URL Metadata Date  \
Department        Object Number
The American Wing 1979.486.1                    NaN           NaN
                  1980.264.5                    NaN           NaN
                  67.265.9                      NaN           NaN
                  67.265.10                     NaN           NaN
                  67.265.11                     NaN           NaN

                                                               Repository  \
Department        Object Number
The American Wing 1979.486.1     Metropolitan Museum of Art, New York, NY
                  1980.264.5     Metropolitan Museum of Art, New York, NY
                  67.265.9       Metropolitan Museum of Art, New York, NY
                  67.265.10      Metropolitan Museum of Art, New York, NY
                  67.265.11      Metropolitan Museum of Art, New York, NY

                                Tags Tags AAT URL Tags Wikidata URL  \
Department        Object Number
The American Wing 1979.486.1     NaN          NaN               NaN
                  1980.264.5     NaN          NaN               NaN
                  67.265.9       NaN          NaN               NaN
                  67.265.10      NaN          NaN               NaN
                  67.265.11      NaN          NaN               NaN

                                AccessionYear_clean   Dept_Group
Department        Object Number
The American Wing 1979.486.1                   1979  Western Art
                  1980.264.5                   1980  Western Art
                  67.265.9                     1967  Western Art
                  67.265.10                    1967  Western Art
                  67.265.11                    1967  Western Art

[5 rows x 54 columns]

Ch 11 transformations

- Convert between string and datetime
- Generate a date range

In [17]:
# convert accession yr to datetime
metobj_df["AccessionYear_dt"] = pd.to_datetime(
    metobj_df["AccessionYear"], 
    errors="coerce"
)

In [18]:
# Generate a date range
date_range = pd.date_range(start="1800-01-01", periods=100, freq="Y")

In [19]:
# preview
date_range

DatetimeIndex(['1800-12-31', '1801-12-31', '1802-12-31', '1803-12-31',
               '1804-12-31', '1805-12-31', '1806-12-31', '1807-12-31',
               '1808-12-31', '1809-12-31', '1810-12-31', '1811-12-31',
               '1812-12-31', '1813-12-31', '1814-12-31', '1815-12-31',
               '1816-12-31', '1817-12-31', '1818-12-31', '1819-12-31',
               '1820-12-31', '1821-12-31', '1822-12-31', '1823-12-31',
               '1824-12-31', '1825-12-31', '1826-12-31', '1827-12-31',
               '1828-12-31', '1829-12-31', '1830-12-31', '1831-12-31',
               '1832-12-31', '1833-12-31', '1834-12-31', '1835-12-31',
               '1836-12-31', '1837-12-31', '1838-12-31', '1839-12-31',
               '1840-12-31', '1841-12-31', '1842-12-31', '1843-12-31',
               '1844-12-31', '1845-12-31', '1846-12-31', '1847-12-31',
               '1848-12-31', '1849-12-31', '1850-12-31', '1851-12-31',
               '1852-12-31', '1853-12-31', '1854-12-31', '1855-12-31',
               '1856-12-31', '1857-12-31', '1858-12-31', '1859-12-31',
               '1860-12-31', '1861-12-31', '1862-12-31', '1863-12-31',
               '1864-12-31', '1865-12-31', '1866-12-31', '1867-12-31',
               '1868-12-31', '1869-12-31', '1870-12-31', '1871-12-31',
               '1872-12-31', '1873-12-31', '1874-12-31', '1875-12-31',
               '1876-12-31', '1877-12-31', '1878-12-31', '1879-12-31',
               '1880-12-31', '1881-12-31', '1882-12-31', '1883-12-31',
               '1884-12-31', '1885-12-31', '1886-12-31', '1887-12-31',
               '1888-12-31', '1889-12-31', '1890-12-31', '1891-12-31',
               '1892-12-31', '1893-12-31', '1894-12-31', '1895-12-31',
               '1896-12-31', '1897-12-31', '1898-12-31', '1899-12-31'],
              dtype='datetime64[ns]', freq='A-DEC')

In [20]:
# That didn't tell me a whole lot so let's try a different method that I was originally going to partially do for chapter 7.

# bin 'em
bins = list(range(1850, 2051, 50))

# label 'em
labels = [
    "1850–1899",
    "1900–1949",
    "1950–1999",
    "2000–2049"
]

#
metobj_df["YearGroup_50"] = pd.cut(
    metobj_df["AccessionYear_clean"],
    bins=bins,
    labels=labels,
    right=False
)

# count 'em
metobj_df["YearGroup_50"].value_counts().sort_index()

YearGroup_50
1850–1899     25223
1900–1949    180376
1950–1999    202224
2000–2049     73271
Name: count, dtype: int64